# Generated by Django 5.0.6 on 2024-05-16 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gender_alter_user_options_alter_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gender'),
        ),
    ]
