# Generated by Django 5.0.6 on 2024-05-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_news_datatime_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
    ]
