from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddWindow():
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 340)
        MainWindow.setMaximumSize(QtCore.QSize(790, 100000))
        MainWindow.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setEnabled(True)
        self.mainLabel.setGeometry(QtCore.QRect(20, 10, 521, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.mainLabel.setFont(font)
        self.mainLabel.setAutoFillBackground(False)
        self.mainLabel.setScaledContents(False)
        self.mainLabel.setWordWrap(False)
        self.mainLabel.setOpenExternalLinks(False)
        self.mainLabel.setObjectName("mainLabel")
        self.inputCodeOfTrain = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCodeOfTrain.setGeometry(QtCore.QRect(130, 70, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputCodeOfTrain.setFont(font)
        self.inputCodeOfTrain.setMouseTracking(True)
        self.inputCodeOfTrain.setTabletTracking(False)
        self.inputCodeOfTrain.setAutoFillBackground(False)
        self.inputCodeOfTrain.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.inputCodeOfTrain.setMaxLength(3)
        self.inputCodeOfTrain.setDragEnabled(False)
        self.inputCodeOfTrain.setReadOnly(False)
        self.inputCodeOfTrain.setClearButtonEnabled(True)
        self.inputCodeOfTrain.setObjectName("inputCodeOfTrain")
        self.labelCode = QtWidgets.QLabel(self.centralwidget)
        self.labelCode.setGeometry(QtCore.QRect(20, 80, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCode.setFont(font)
        self.labelCode.setObjectName("labelCode")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(395, 120, 20, 141))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.departurePoint = QtWidgets.QComboBox(self.centralwidget)
        self.departurePoint.setGeometry(QtCore.QRect(180, 130, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.departurePoint.setFont(font)
        self.departurePoint.setObjectName("departurePoint")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.departurePoint.addItem("")
        self.labelArrivalPoint = QtWidgets.QLabel(self.centralwidget)
        self.labelArrivalPoint.setGeometry(QtCore.QRect(420, 130, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelArrivalPoint.setFont(font)
        self.labelArrivalPoint.setObjectName("labelArrivalPoint")
        self.arrivalPoint = QtWidgets.QComboBox(self.centralwidget)
        self.arrivalPoint.setGeometry(QtCore.QRect(560, 130, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.arrivalPoint.setFont(font)
        self.arrivalPoint.setObjectName("arrivalPoint")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.arrivalPoint.addItem("")
        self.labelDeparturePoint = QtWidgets.QLabel(self.centralwidget)
        self.labelDeparturePoint.setGeometry(QtCore.QRect(20, 130, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelDeparturePoint.setFont(font)
        self.labelDeparturePoint.setObjectName("labelDeparturePoint")
        self.labelDepartureDate = QtWidgets.QLabel(self.centralwidget)
        self.labelDepartureDate.setGeometry(QtCore.QRect(20, 180, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelDepartureDate.setFont(font)
        self.labelDepartureDate.setObjectName("labelDepartureDate")
        self.departureDate = QtWidgets.QDateEdit(self.centralwidget)
        self.departureDate.setGeometry(QtCore.QRect(180, 180, 110, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.departureDate.setFont(font)
        self.departureDate.setInputMethodHints(QtCore.Qt.ImhDate | QtCore.Qt.ImhPreferNumbers)
        self.departureDate.setObjectName("departureDate")
        self.labelArrivalDate = QtWidgets.QLabel(self.centralwidget)
        self.labelArrivalDate.setGeometry(QtCore.QRect(420, 180, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelArrivalDate.setFont(font)
        self.labelArrivalDate.setObjectName("labelArrivalDate")
        self.arrivalDate = QtWidgets.QDateEdit(self.centralwidget)
        self.arrivalDate.setGeometry(QtCore.QRect(560, 180, 110, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.arrivalDate.setFont(font)
        self.arrivalDate.setInputMethodHints(QtCore.Qt.ImhDate | QtCore.Qt.ImhPreferNumbers)
        self.arrivalDate.setObjectName("arrivalDate")
        self.labelDepartureTime = QtWidgets.QLabel(self.centralwidget)
        self.labelDepartureTime.setGeometry(QtCore.QRect(20, 230, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelDepartureTime.setFont(font)
        self.labelDepartureTime.setObjectName("labelDepartureTime")
        self.departureTime = QtWidgets.QTimeEdit(self.centralwidget)
        self.departureTime.setGeometry(QtCore.QRect(180, 230, 118, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.departureTime.setFont(font)
        self.departureTime.setInputMethodHints(QtCore.Qt.ImhPreferNumbers | QtCore.Qt.ImhTime)
        self.departureTime.setObjectName("departureTime")
        self.labelArrivalTime = QtWidgets.QLabel(self.centralwidget)
        self.labelArrivalTime.setGeometry(QtCore.QRect(420, 230, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelArrivalTime.setFont(font)
        self.labelArrivalTime.setObjectName("labelArrivalTime")
        self.arrivalTime = QtWidgets.QTimeEdit(self.centralwidget)
        self.arrivalTime.setGeometry(QtCore.QRect(560, 230, 118, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.arrivalTime.setFont(font)
        self.arrivalTime.setInputMethodHints(QtCore.Qt.ImhPreferNumbers | QtCore.Qt.ImhTime)
        self.arrivalTime.setObjectName("arrivalTime")
        self.pushButtonToAdd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonToAdd.setGeometry(QtCore.QRect(650, 290, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonToAdd.setFont(font)
        self.pushButtonToAdd.setObjectName("pushButtonToAdd")
        self.pushButtonToCancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonToCancel.setGeometry(QtCore.QRect(520, 290, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonToCancel.setFont(font)
        self.pushButtonToCancel.setObjectName("pushButtonToCancel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Добавление"))
        self.mainLabel.setText(_translate("MainWindow", "Добавление нового маршрута"))
        self.inputCodeOfTrain.setText(_translate("MainWindow", "000"))
        self.labelCode.setText(_translate("MainWindow", "Номер поезда"))
        self.departurePoint.setItemText(0, _translate("MainWindow", "Выбрать пункт"))
        self.departurePoint.setItemText(1, _translate("MainWindow", "Минск"))
        self.departurePoint.setItemText(2, _translate("MainWindow", "Брест"))
        self.departurePoint.setItemText(3, _translate("MainWindow", "Витебск"))
        self.departurePoint.setItemText(4, _translate("MainWindow", "Гомель"))
        self.departurePoint.setItemText(5, _translate("MainWindow", "Гродно"))
        self.departurePoint.setItemText(6, _translate("MainWindow", "Могилев"))
        self.departurePoint.setItemText(7, _translate("MainWindow", "Жлобин"))
        self.departurePoint.setItemText(8, _translate("MainWindow", "Калинковичи"))
        self.departurePoint.setItemText(9, _translate("MainWindow", "Лида"))
        self.departurePoint.setItemText(10, _translate("MainWindow", "Орша"))
        self.departurePoint.setItemText(11, _translate("MainWindow", "Пинск"))
        self.departurePoint.setItemText(12, _translate("MainWindow", "Полоцк"))
        self.departurePoint.setItemText(13, _translate("MainWindow", "Адлер"))
        self.departurePoint.setItemText(14, _translate("MainWindow", "Москва"))
        self.departurePoint.setItemText(15, _translate("MainWindow", "С.Петербург"))
        self.labelArrivalPoint.setText(_translate("MainWindow", "Пункт прибытия"))
        self.arrivalPoint.setItemText(0, _translate("MainWindow", "Выбрать пункт"))
        self.arrivalPoint.setItemText(1, _translate("MainWindow", "Минск"))
        self.arrivalPoint.setItemText(2, _translate("MainWindow", "Брест"))
        self.arrivalPoint.setItemText(3, _translate("MainWindow", "Витебск"))
        self.arrivalPoint.setItemText(4, _translate("MainWindow", "Гомель"))
        self.arrivalPoint.setItemText(5, _translate("MainWindow", "Гродно"))
        self.arrivalPoint.setItemText(6, _translate("MainWindow", "Могилев"))
        self.arrivalPoint.setItemText(7, _translate("MainWindow", "Жлобин"))
        self.arrivalPoint.setItemText(8, _translate("MainWindow", "Калинковичи"))
        self.arrivalPoint.setItemText(9, _translate("MainWindow", "Лида"))
        self.arrivalPoint.setItemText(10, _translate("MainWindow", "Орша"))
        self.arrivalPoint.setItemText(11, _translate("MainWindow", "Пинск"))
        self.arrivalPoint.setItemText(12, _translate("MainWindow", "Полоцк"))
        self.arrivalPoint.setItemText(13, _translate("MainWindow", "Адлер"))
        self.arrivalPoint.setItemText(14, _translate("MainWindow", "Москва"))
        self.arrivalPoint.setItemText(15, _translate("MainWindow", "С.Петербург"))
        self.labelDeparturePoint.setText(_translate("MainWindow", "Пункт отправления"))
        self.labelDepartureDate.setText(_translate("MainWindow", "Дата отправления"))
        self.labelArrivalDate.setText(_translate("MainWindow", "Дата прибытия"))
        self.labelDepartureTime.setText(_translate("MainWindow", "Время отправления"))
        self.labelArrivalTime.setText(_translate("MainWindow", "Время прибытия"))
        self.pushButtonToAdd.setText(_translate("MainWindow", "Добавить"))
        self.pushButtonToCancel.setText(_translate("MainWindow", "Отменить"))
